import { toKebab } from "@malilion/block-ui-tokens";
import { defaultThemeName, themes } from "./themes.js";
import type { BlockTheme, BlockThemeName } from "./types.js";

/** CSS variable name for a theme role. `background` maps to the PRD's `--block-bg`. */
export function themeVar(role: keyof BlockTheme): string {
  if (role === "background") return "--block-bg";
  if (role === "texture") return "--block-texture";
  return `--block-${toKebab(role)}`;
}

export function themeEntries(theme: BlockTheme): Array<[string, string]> {
  return (Object.keys(theme) as Array<keyof BlockTheme>).map((role) => {
    const value = theme[role];
    if (role === "texture") return [themeVar(role), `var(--block-texture-${toKebab(value)})`];
    return [themeVar(role), value.startsWith("#") ? value.toLowerCase() : value];
  });
}

function block(selector: string, theme: BlockTheme): string {
  const body = themeEntries(theme)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
  return `${selector} {\n  color-scheme: dark;\n${body}\n}`;
}

/** Generates `themes.css`. The default theme also applies to `:root`. */
export function generateThemesCss(): string {
  const blocks = (Object.keys(themes) as BlockThemeName[]).map((name) => {
    const selector =
      name === defaultThemeName ? `:root,\n[data-theme="${name}"]` : `[data-theme="${name}"]`;
    return block(selector, themes[name]);
  });
  return `/* Generated by @malilion/block-ui-themes — do not edit by hand. Run \`pnpm generate\`. */\n${blocks.join("\n\n")}\n`;
}
