packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - globals@17.13.0
  - vite@8.3.2
  - "@malilion/block-ui-icons@0.6.1"
  - "@malilion/block-ui-react@0.6.1"
  - "@malilion/block-ui-themes@0.6.1"
  - "@malilion/block-ui-tokens@0.6.1"
