import { colors, materials } from "./colors.js";
import { spacing } from "./spacing.js";
import { fontFamily, fontSize, fontWeight, letterSpacing, lineHeight } from "./typography.js";
import { radius } from "./radius.js";
import { border, shadow } from "./shadow.js";
import { easing, motion } from "./motion.js";
import { sizes } from "./sizes.js";
import { zIndex } from "./zIndex.js";
import { textures } from "./textures.js";
import { relativeLuminance } from "./contrast.js";

/** camelCase / PascalCase → kebab-case (`grassDark` → `grass-dark`, `2xl` → `2xl`). */
export function toKebab(value: string): string {
  return value.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/** CSS variable name for a color token. `background` maps to the PRD's `--block-bg`. */
export function colorVar(token: keyof typeof colors): string {
  return token === "background" ? "--block-bg" : `--block-${toKebab(token)}`;
}

type Entries = Array<[string, string]>;

function group(prefix: string, record: Record<string | number, string>): Entries {
  return Object.entries(record).map(([key, value]) => [`--block-${prefix}${toKebab(key)}`, value]);
}

/** Every token as `[cssVariableName, value]`, in output order. */
export function tokenEntries(): Entries {
  const colorEntries: Entries = Object.entries(colors).map(([key, value]) => [
    colorVar(key as keyof typeof colors),
    value.toLowerCase(),
  ]);

  return [
    ...colorEntries,
    ...group("space-", spacing),
    ...group("font-", fontFamily),
    ...group("font-size-", fontSize),
    ...group("font-weight-", fontWeight),
    ...group("line-height-", lineHeight),
    ...group("letter-spacing-", letterSpacing),
    ...group("radius-", radius),
    ["--block-border-width", border.width],
    ["--block-border-width-thin", border.widthThin],
    ["--block-border-color", border.color.toLowerCase()],
    ...group("shadow-", shadow),
    ...group("duration-", motion),
    ...group("ease-", easing),
    ...group("size-", sizes),
    ...group("z-", zIndex),
    ...group("texture-", textures),
  ];
}

/**
 * `[data-material="…"]` rules. Components set `data-material` and read the
 * generic `--block-mat*` variables, so every material variant stays token-driven.
 */
export function materialCss(): string {
  return materials
    .map((material) => {
      const name = toKebab(material);
      const onKey =
        `on${material.charAt(0).toUpperCase()}${material.slice(1)}` as keyof typeof colors;
      const lightText = relativeLuminance(colors[onKey]) > 0.5;
      return [
        `[data-material="${name}"] {`,
        `  --block-mat: var(--block-${name});`,
        `  --block-mat-light: var(--block-${name}-light);`,
        `  --block-mat-dark: var(--block-${name}-dark);`,
        `  --block-mat-on: var(--block-on-${name});`,
        `  --block-mat-text-shadow: ${lightText ? "var(--block-shadow-text)" : "var(--block-shadow-text-light)"};`,
        `}`,
      ].join("\n");
    })
    .join("\n");
}

/** Generates `tokens.css` — the CSS custom properties for every design token. */
export function generateTokensCss(): string {
  const body = tokenEntries()
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
  return `/* Generated by @block-ui/tokens — do not edit by hand. Run \`pnpm generate\`. */\n:root {\n${body}\n}\n\n${materialCss()}\n`;
}
